### ISSUE TITLE
Can't run no commands

### ISSUE THREAD

**Issue by gnutix** [metaodi/cabdriver#112]
I'd guess the project is not locking dependencies strictly enough and it hasn't been installed by anyone for years ?

```
$ node --version
v12.16.3

$ cab -V
3.0.0

$ cabdriver --calendar
/usr/lib/node_modules/cabdriver/node_modules/bluebird/js/release/promisify.js:270
        throw new TypeError("expecting a function but got " + util.classString(fn));
        ^

TypeError: expecting a function but got [object Object]
    at Function.Promise.promisify (/usr/lib/node_modules/cabdriver/node_modules/bluebird/js/release/promisify.js:270:15)
    at new Git (/usr/lib/node_modules/cabdriver/lib/source/git.js:19:41)
    at /usr/lib/node_modules/cabdriver/cli/fetch.js:176:20
    at /usr/lib/node_modules/cabdriver/node_modules/lodash/lodash.js:13401:38
    at /usr/lib/node_modules/cabdriver/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/usr/lib/node_modules/cabdriver/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (/usr/lib/node_modules/cabdriver/node_modules/lodash/lodash.js:13400:7)
    at FetchCli.getSources (/usr/lib/node_modules/cabdriver/cli/fetch.js:175:25)
    at FetchCli.querySources (/usr/lib/node_modules/cabdriver/cli/fetch.js:150:26)
    at FetchCli.run (/usr/lib/node_modules/cabdriver/cli/fetch.js:50:12)
    at Object.<anonymous> (/usr/lib/node_modules/cabdriver/cabdriver-fetch.js:29:7)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by metaodi** [comment]
Fixed with #117
